In [50]:
import pixiedust
import numpy as np
x = np.random.rand(3,4)
y = np.random.rand(2,4)
a = [[1,1,1,1],[2,2,2,2],[3,3,3,3]]
b = [[4,4,4,4],[5,5,5,5]]
c = np.asarray([10,20])
d = np.asarray([3,4,5])

In [55]:
%qtconsole
e = c + d[:,np.newaxis]
print(np.shape(d[:,np.newaxis]))
print(e)


(3, 1)
[[13 23]
 [14 24]
 [15 25]]


In [28]:
# dists = -2 * np.dot(x,np.transpose(y))
temp1 = np.sum(y,axis=1)
temp2 = np.sum(x, axis=1)
dists = temp1 + temp2

ValueError: operands could not be broadcast together with shapes (2,) (3,) 

In [15]:
%qtconsole
print(x,'\n\n')
print(y,'\n\n')
# print(dists,'\n\n')
print(np.sum(x,axis=1),'\n\n')
print(np.sum(y,axis=1),'\n\n')

[[0.99432345 0.38961013 0.53952133 0.21774749]
 [0.5628507  0.47836103 0.86961797 0.81181185]
 [0.42026004 0.08430361 0.06949282 0.31500738]] 


[[0.50837089 0.9223527  0.24050061 0.934145  ]
 [0.72316872 0.09508896 0.51547515 0.63117662]] 


[2.1412024  2.72264156 0.88906385] 


[2.6053692  1.96490944] 


